# Generated by Django 4.0.4 on 2022-05-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Алгоритм консенсуса')),
            ],
            options={
                'verbose_name': 'Алгоритм консенсуса',
                'verbose_name_plural': 'Алгоритмы консенсуса',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Создатель')),
                ('consensus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coins.consensus')),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
                'ordering': ['pk'],
            },
        ),
    ]
